katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_catalog

app_name = 'catalog'

urlpatterns = [
    path('', show_catalog, name='show_catalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/',include('todolist.urls')),
    path('watchlistcune',include('watchlistcune.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import *

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name="show_todolist"),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'), 
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create_task'),
    path('update-task/<str:key>/', task_status, name='task_status'),
    path('delete-task/<str:key>/', delete_task, name="delete_task"),
    path('json/',show_json,name="show_json"),
    path('add/', create_todolist_ajax, name='create_todolist_ajax'),
    path('json_ajax/', show_todolist_ajax, name='show_todolist_ajax'), 
]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

class ToDoList(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    date = models.DateField()
    title = models.CharField(max_length=100)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)
    

todolist/views.py
from asyncio.base_tasks import _task_print_stack
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.http import HttpRequest
from django.core import serializers

from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from todolist.models import ToDoList

from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='login/')
def show_todolist(request):
    todolist_data = ToDoList.objects.filter(user=request.user)
    context = {
    'todo': todolist_data,
    'username' : request.user,
    }
    return render(request, "todolist.html",context=context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {
    }
    return render(request, 'login.html', context)

@login_required(login_url='login/')
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='login/')
def create_task(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')

        if title != "" and description != "":
            ToDoList.objects.create(title=title, description=description, date=datetime.date.today(), user=request.user)
            info_message = 'Task "{title}" telah berhasil disimpan!'.format(title= title)
            messages.info(request, info_message)
            return HttpResponseRedirect(reverse("todolist:show_todolist")) 
        
        messages.info(request, 'Judul atau Deskripsi belum diisi!')

    return render(request, "create.html")


@login_required(login_url='/todolist/login/')
def task_status(request, key):
    task = ToDoList.objects.get(
        user = request.user,
        pk = key
    )
    task.is_finished = not task.is_finished
    task.save()
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
def delete_task(request, key):
    task = ToDoList.objects.get(
        user = request.user,
        pk = key
    )
    task.delete()
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
def show_json(request):
    data = ToDoList.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")
    
@login_required(login_url='/todolist/login/')
def show_todolist_ajax(request):
    tasklist = ToDoList.objects.filter(user=request.user)
    context = {
        'tasks' : tasklist,
        'username' : request.user,
    }
    return render(request, "todolist.html", context)

@csrf_exempt
def create_todolist_ajax(request):
    if request.method == 'POST':

        title = request.POST.get('title')
        description = request.POST.get('description')
        task = ToDoList.objects.create(title=title, description=description, date=datetime.date.today(), user=request.user)
        
        result = {
            'fields':{
                'title':task.title,
                'description':task.description,
                'date':task.date,
            },
            'pk':task.pk
        }
        print(result)
        return JsonResponse(result)

todolist/templates/create.html
{% extends 'base.html' %} 
{% block meta %}
<title>Todolist</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
{% endblock meta %} 

{% block content %}
<body style="background-image: url(https://thumbs.dreamstime.com/b/seamless-pattern-repeatable-background-website-wallpaper-textile-printing-texture-editable-vector-87678560.jpg); background-repeat: repeat; background-size: cover; background-position: center; height: 100%; width: 100%;">
  <div class="container h-100" style="background-color:#fff;border-radius: 2rem; margin-top: 10%; width:50%; height: 50%; box-shadow: 10px 10px 100px rgb(166, 166, 166);">
    <div class="row h-100 justify-content-center align-items-center" style="margin:4%;">
        <div class="col-10">
          <!-- Form -->
          <form class="form-example" action="" method="post" style="padding:4%">
            {% csrf_token %}
            <b>
              <h1 ALIGN="center">Let's Add your Task!</h1>
            </b>
            <p class="description" ALIGN="center">Silahkan masukan judul dan deskripsi tugasmu</p>

            {% if messages %}
                {% for message in messages %}
                    <p class="messsage" ALIGN="center" style="color:red">{{message}}</p>
                {% endfor %}
            {% endif %}   

            <!-- Input fields -->
            <div class="form-group" style="margin-top:4%;">
              <label for="judul">Judul:</label>
              <input
              type="text"
              name="title"
              placeholder="Judul..."
              class="form-control"
            />
            </div>

            <div class="form-group" style="margin-top:4%;">
              <label for="description">Deskripsi:</label>
              <input
              type="text"
              name="description"
              placeholder="Deskripsi..."
              class="form-control"
            />
            </div>

            <button type="submit" class="btn btn-primary btn-customized" style="margin-top:4%;" value="Submit">Submit</button>

          </form>
  <!-- Form end -->
        </div>
    </div>
</div>
</body>
{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %} 

{% block meta %}
<title>Login</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
{% endblock meta %} 

{% block content %}
<body style="background-image: url(https://thumbs.dreamstime.com/b/seamless-pattern-repeatable-background-website-wallpaper-textile-printing-texture-editable-vector-87678560.jpg); background-repeat: repeat; background-size: cover; background-position: center; height: 100%; width: 100%;">
  <div class="container h-100" style="background-color:#fff;border-radius: 2rem; margin-top: 10%; width:50%; height: 50%; box-shadow: 10px 10px 100px rgb(166, 166, 166);">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-10">
              <!-- Form -->
              <form class="form-example" action="" method="post" style="padding:4%">
                {% csrf_token %}
                <b>
                  <h1 ALIGN="center">Welcome to Your Personal Task Manager!</h1>
                </b>
                <p class="description" ALIGN="center">Login disini untuk membuat dan memantau tugasmu</p>

                {% if messages %}
                    {% for message in messages %}
                        <p class="messsage" ALIGN="center" style="color:red">{{ message }}</p>
                    {% endfor %}
                {% endif %}   

                <!-- Input fields -->
                <div class="form-group" style="margin-top:4%;">
                  <label for="username">Username:</label>
                  <input type="text" class="form-control username" id="username" placeholder="Username..." name="username">
                </div>


                <div class="form-group" style="margin-top:4%;">
                  <label for="password">Password:</label>
                  <input type="password" class="form-control password" id="password" placeholder="Password..." name="password">
                </div>

                <button type="submit" class="btn btn-primary btn-customized" style="margin-top:4%;">Login</button>

                <p style="margin-top:4%;">
                  Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>
                </p>
              </form>
      <!-- Form end -->
            </div>
        </div>
    </div>
</body>
{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %} 
{% block meta %}
<title>Register</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
{% endblock meta %} 

{% block content %}
<body style="background-image: url(https://thumbs.dreamstime.com/b/seamless-pattern-repeatable-background-website-wallpaper-textile-printing-texture-editable-vector-87678560.jpg); background-repeat: repeat; background-size: cover; background-position: center; height: 100%; width: 100%;">
  <div class="container h-100" style="background-color:#fff;border-radius: 2rem; width:90%; height: 80%; box-shadow: 10px 10px 100px rgb(166, 166, 166);">
    <div class="row h-100 justify-content-center align-items-center" style="margin:4%">
        <div>
         <h1 ALIGN="center" style="margin-top:4%">Account Registration</h1>
        
         <div style="background-color:#fff;border-radius: 2rem; width:90%; height: 80%; box-shadow: 10px 10px 100px rgb(166, 166, 166);"></div>
          <form method="POST">
            {% csrf_token %}
            <table>
              {{ form.as_table }}
              <tr>
                <td>
                  <button type="submit" class="btn btn-primary" style="margin-top:4%;">Daftar</button>
                </td>
              </tr>
            </table>
          </form>
        </div>

  {% if messages %}
    {% for message in messages %}
    <p style="color:red;">{{ message }}</p>
    {% endfor %}
  {% endif %}
</div>
</div>
</div>
</body>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
<title>Todolist</title>
<meta name="viewport", content="width=device-width, initial-scale=1.0"></meta>
{% endblock meta %}

{% block content %}
<head>
    <!-- Bootstrap CSS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

        <!-- Script to get JSON file and display its content -->
        <script type="text/javascript" language="javascript">
        $(document).ready(function() {
            $.get("/todolist/json/", function(todolist) {
                console.log(todolist);
                for (i = 0; i < todolist.length; i++){
                    $(".card-grid").append(
                    `       
                    <div>
                        <div class="card" style="margin:2%;">
                            <div class="card-header" style="background-color: rgb(195, 107, 184);">
                                <h4 class="card-title">${todolist[i].fields.title}</h4>
                                <p class="card-text">Created on: ${todolist[i].fields.date}</p>
                            </div>

                            <div class="card-body">
                                <p class="card-text">${todolist[i].fields.description}</p>
                            </div>
                         <div>
                    <div>
                        `)
                }
            });
            $("#submit").click(function(){
              $.post("/todolist/add/", {
                title : $('#title').val(),
                description: $('#description').val()},
                function (result) {
                  $(".card-grid").append(
                        
                    `       
                    <div>
                        <div class="card" style="margin:2%;">
                            <div class="card-header" style="background-color: rgb(195, 107, 184);">
                                <h4 class="card-title">${result.fields.title}</h4>
                                <p class="card-text">Created on: ${result.fields.date}</p>
                            </div>

                            <div class="card-body">
                                <p class="card-text">${result.fields.description}</p>
                            </div>
                         <div>
                    <div>
                        `)
                  $('#title').val(''),
                  $('#description').val('')
                }
                )
              })
        }); 
        </script>
</head>

<body style="background-image: url(https://thumbs.dreamstime.com/b/seamless-pattern-repeatable-background-website-wallpaper-textile-printing-texture-editable-vector-87678560.jpg); background-repeat: repeat; background-size: cover; background-position: center; height: 100%; width: 100%;">
    <div ALIGN = "center">
        <h1 ALIGN = "center">Let's get your task done! 🤩</h1>
        <h3 ALIGN = "center">Current user: {{username}}</h3>

        <div>
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                ✚ Tambah Task Baru
            </button>
            <button class="btn btn-danger" >
            <a href="{% url 'todolist:logout' %}" style="color: #fff; text-decoration: none;">
                ⇲ Logout
            </a>
            </button>
        </div>
    </div>

  
  <!-- Modal -->
  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel">Add Task</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <!-- Form -->
          <form class="form-example" action="" method="post" style="padding:4%">
            {% csrf_token %}
            <b>
              <h2 ALIGN="center">Let's Add your Task!</h2>
            </b>
            <p class="description" ALIGN="center">Silahkan masukan judul dan deskripsi tugasmu</p>

            <!-- Input fields -->
            <div class="form-group" style="margin-top:4%;">
              <label for="judul">Judul:</label>
              <input
              type="text"
              name="title"
              id ="title"
              placeholder="Judul..."
              class="form-control"
            />
            </div>

            <div class="form-group" style="margin-top:4%;">
              <label for="description">Deskripsi:</label>
              <input
              type="text"
              name="description"
              id="description"
              placeholder="Deskripsi..."
              class="form-control"
            />
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" id="submit" data-bs-dismiss="modal">Tambahkan</button>
        </div>
      </div>
    </div>
  </div>

<!-- Block container grid card  -->
<div class="card-grid" style=" display: grid; grid-template-columns: auto auto auto auto; gap: 10px; padding: 10px;"></div>
</body>

{% endblock content %}

todolist/templates/todolist_backup.html
{% extends 'base.html' %} 
{% block meta %}
<title>Todolist</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
{% endblock meta %} 

{% block content %}
<body style="background-image: url(https://thumbs.dreamstime.com/b/seamless-pattern-repeatable-background-website-wallpaper-textile-printing-texture-editable-vector-87678560.jpg); background-repeat: repeat; background-size: cover; background-position: center; height: 100%; width: 100%;">
  <div ALIGN = "center">
    <h1 ALIGN = "center">Let's get your task done! 🤩</h1>
    <h3 ALIGN = "center">Current user: {{username}}</h3>
    {% if messages %}
      {% for message in messages %}
      <p style="color: green;">{{ message }}</p>
      {% endfor %}
    {% endif %}

    <div>
      <button class="btn btn-primary btn-customized">
        <a href="{% url 'todolist:create_task' %}" style="color: #fff; text-decoration: none;">
          ✚ Tambah Task Baru
        </a>
      </button>
      <!-- <button class="btn btn-primary">
        <a href="{% url 'todolist:show_todolist_ajax' %}" class="link-light">To Do List versi AJAX</a>
      </button>  -->
      <button class="btn btn-danger" >
        <a href="{% url 'todolist:logout' %}" style="color: #fff; text-decoration: none;">
          ⇲ Logout
        </a>
      </button>
    </div>
  </div>

  <div>
  <div>
    <div  class="card-grid" style=" display: grid; grid-template-columns: auto auto auto auto; gap: 10px; padding: 10px;">
    {% if todo %}
      {% for task in todo %}
      <div class="card" style="margin:2%;">
        <div class="card-header" style="background-color: rgb(195, 107, 184);">
          <h4 class="card-title">{{task.title}}</h4>
          <p class="card-text">Created on: {{task.date}}</p>

          {% if task.is_finished %} 
          <p style="background-color: rgb(191, 255, 127); color: rgb(106, 146, 66);padding:1% 1% 1% 2%; width:50%; border-radius: 2rem;">
            Completed ✅
          </p>
          {% else %} 
          <p style="background-color: rgb(255, 244, 180); color:rgb(108, 103, 73); padding:1% 1% 1% 2%; width:50%; border-radius: 2rem;">
            Pending ⌛️
          </p>
          {% endif %}

        </div>

        <div class="card-body">
          <p class="card-text">{{task.description}}</p>
        </div>
        
        <div class="card-footer">
          <button class="btn" style="margin-top:4%;background-color: blueviolet;">
            <a href="{% url 'todolist:task_status' task.pk %}" style="color: #fff; text-decoration: none;">🔄 Change Status</a>
          </button> 
          <button class="btn btn-warning" style="margin-top:4%;">
            <a href="{% url 'todolist:delete_task' task.pk %}" style="color: #fff; text-decoration: none;">🗑 Delete Task</a>
          </button> 
        </div>
      </div>

    {% endfor %}
    {% else %}
    {% endif %}
  </div>
</div>
</div>
</body>
{% endblock content %}